"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { usePlan } from "@/context/PlanContext";
import { Dumbbell } from "lucide-react";

export default function Navbar() {
  const pathname = usePathname();
    const { todayPlan, savedPlan } = usePlan();

      return (
          <nav className="bg-neutral-900 border-b border-neutral-800 sticky top-0 z-50 px-4 py-3">
                <div className="max-w-6xl mx-auto flex items-center justify-between">
                        <Link href="/" className="flex items-center gap-2 font-black text-xl tracking-wider text-white">
                                  <Dumbbell className="w-6 h-6 text-[#ccff00]" />
                                            <span>FITLOG</span>
                                                    </Link>

                                                            <div className="flex items-center gap-6 text-sm font-semibold">
                                                                      <Link
                                                                                  href="/"
                                                                                              className={pathname === "/" ? "text-[#ccff00] underline underline-offset-4" : "text-neutral-400 hover:text-white"}
                                                                                                        >
                                                                                                                    Workout
                                                                                                                              </Link>
                                                                                                                                        <Link
                                                                                                                                                    href="/my-plan"
                                                                                                                                                                className={pathname === "/my-plan" ? "text-[#ccff00] underline underline-offset-4" : "text-neutral-400 hover:text-white"}
                                                                                                                                                                          >
                                                                                                                                                                                      My Plan
                                                                                                                                                                                                </Link>
                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                <div className="flex items-center gap-3">
                                                                                                                                                                                                                          <Link
                                                                                                                                                                                                                                      href="/my-plan"
                                                                                                                                                                                                                                                  className="bg-[#ccff00] text-black font-bold text-xs px-3 py-1 rounded-full flex items-center gap-1.5 hover:opacity-90 transition"
                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                        <span>Plan</span>
                                                                                                                                                                                                                                                                                    <span className="bg-black text-white px-1.5 py-0.5 rounded-full text-[10px]">
                                                                                                                                                                                                                                                                                                  {todayPlan.length}
                                                                                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                                                                                        </Link>

                                                                                                                                                                                                                                                                                                                                  <Link
                                                                                                                                                                                                                                                                                                                                              href="/my-plan"
                                                                                                                                                                                                                                                                                                                                                          className="border border-neutral-600 text-white font-bold text-xs px-3 py-1 rounded-full flex items-center gap-1.5 hover:border-[#ccff00] transition"
                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                <span>Saved</span>
                                                                                                                                                                                                                                                                                                                                                                                            <span className="bg-neutral-800 text-neutral-300 px-1.5 py-0.5 rounded-full text-[10px]">
                                                                                                                                                                                                                                                                                                                                                                                                          {savedPlan.length}
                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }